service: fursorger-backend
org: prosingularity
app: fursorger-backend

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
    - serverless-plugin-optimize
    - serverless-offline # must come after typescript

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-central-1
    stage: prod # for sls offline, access via localhost:3000/prod/level, for sls deploy access via aws-domain/prod/prod/level
    environment:
        POSTGRES_USER: ${env:POSTGRES_USER}
        POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
        POSTGRES_DATABASE_NAME: ${env:POSTGRES_DATABASE_NAME}
        POSTGRES_HOST: ${env:POSTGRES_HOST}
        POSTGRES_PORT: ${env:POSTGRES_PORT}
        RUNTIME: ${env:RUNTIME}

functions:
    fursorgerBackend: # The name of the lambda function
        # The module 'handler' is exported in the file 'src/lambda'
        handler: src/lambda.handler
        events:
            - http:
                  path: /{any+}
                  method: any
